version : '3.4'
services:
  web:
    build :
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
      ##add this service for executing tests
  tests:
    build :
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
      #override comman
    command: ["npm","run","test"]